/* Generated by the protocol buffer compiler.  DO NOT EDIT! */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C_NO_DEPRECATED
#define PROTOBUF_C_NO_DEPRECATED
#endif

#include "PGcodec.pb-c.h"
void   pgcodec__root_ent__init
                     (PGcodec__RootEnt         *message)
{
  static PGcodec__RootEnt init_value = PGCODEC__ROOT_ENT__INIT;
  *message = init_value;
}
size_t pgcodec__root_ent__get_packed_size
                     (const PGcodec__RootEnt *message)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &pgcodec__root_ent__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t pgcodec__root_ent__pack
                     (const PGcodec__RootEnt *message,
                      uint8_t       *out)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &pgcodec__root_ent__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t pgcodec__root_ent__pack_to_buffer
                     (const PGcodec__RootEnt *message,
                      ProtobufCBuffer *buffer)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &pgcodec__root_ent__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
PGcodec__RootEnt *
       pgcodec__root_ent__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (PGcodec__RootEnt *)
     protobuf_c_message_unpack (&pgcodec__root_ent__descriptor,
                                allocator, len, data);
}
void   pgcodec__root_ent__free_unpacked
                     (PGcodec__RootEnt *message,
                      ProtobufCAllocator *allocator)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &pgcodec__root_ent__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   pgcodec__root_idx__init
                     (PGcodec__RootIdx         *message)
{
  static PGcodec__RootIdx init_value = PGCODEC__ROOT_IDX__INIT;
  *message = init_value;
}
size_t pgcodec__root_idx__get_packed_size
                     (const PGcodec__RootIdx *message)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &pgcodec__root_idx__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t pgcodec__root_idx__pack
                     (const PGcodec__RootIdx *message,
                      uint8_t       *out)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &pgcodec__root_idx__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t pgcodec__root_idx__pack_to_buffer
                     (const PGcodec__RootIdx *message,
                      ProtobufCBuffer *buffer)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &pgcodec__root_idx__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
PGcodec__RootIdx *
       pgcodec__root_idx__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (PGcodec__RootIdx *)
     protobuf_c_message_unpack (&pgcodec__root_idx__descriptor,
                                allocator, len, data);
}
void   pgcodec__root_idx__free_unpacked
                     (PGcodec__RootIdx *message,
                      ProtobufCAllocator *allocator)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &pgcodec__root_idx__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   pgcodec__table_meta__init
                     (PGcodec__TableMeta         *message)
{
  static PGcodec__TableMeta init_value = PGCODEC__TABLE_META__INIT;
  *message = init_value;
}
size_t pgcodec__table_meta__get_packed_size
                     (const PGcodec__TableMeta *message)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &pgcodec__table_meta__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t pgcodec__table_meta__pack
                     (const PGcodec__TableMeta *message,
                      uint8_t       *out)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &pgcodec__table_meta__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t pgcodec__table_meta__pack_to_buffer
                     (const PGcodec__TableMeta *message,
                      ProtobufCBuffer *buffer)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &pgcodec__table_meta__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
PGcodec__TableMeta *
       pgcodec__table_meta__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (PGcodec__TableMeta *)
     protobuf_c_message_unpack (&pgcodec__table_meta__descriptor,
                                allocator, len, data);
}
void   pgcodec__table_meta__free_unpacked
                     (PGcodec__TableMeta *message,
                      ProtobufCAllocator *allocator)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &pgcodec__table_meta__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   pgcodec__superblock__init
                     (PGcodec__Superblock         *message)
{
  static PGcodec__Superblock init_value = PGCODEC__SUPERBLOCK__INIT;
  *message = init_value;
}
size_t pgcodec__superblock__get_packed_size
                     (const PGcodec__Superblock *message)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &pgcodec__superblock__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t pgcodec__superblock__pack
                     (const PGcodec__Superblock *message,
                      uint8_t       *out)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &pgcodec__superblock__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t pgcodec__superblock__pack_to_buffer
                     (const PGcodec__Superblock *message,
                      ProtobufCBuffer *buffer)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &pgcodec__superblock__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
PGcodec__Superblock *
       pgcodec__superblock__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (PGcodec__Superblock *)
     protobuf_c_message_unpack (&pgcodec__superblock__descriptor,
                                allocator, len, data);
}
void   pgcodec__superblock__free_unpacked
                     (PGcodec__Superblock *message,
                      ProtobufCAllocator *allocator)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &pgcodec__superblock__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor pgcodec__root_ent__field_descriptors[3] =
{
  {
    "key",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(PGcodec__RootEnt, key),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "n_records",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(PGcodec__RootEnt, n_records),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "file_id",
    3,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT64,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(PGcodec__RootEnt, file_id),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned pgcodec__root_ent__field_indices_by_name[] = {
  2,   /* field[2] = file_id */
  0,   /* field[0] = key */
  1,   /* field[1] = n_records */
};
static const ProtobufCIntRange pgcodec__root_ent__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor pgcodec__root_ent__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "PGcodec.RootEnt",
  "RootEnt",
  "PGcodec__RootEnt",
  "PGcodec",
  sizeof(PGcodec__RootEnt),
  3,
  pgcodec__root_ent__field_descriptors,
  pgcodec__root_ent__field_indices_by_name,
  1,  pgcodec__root_ent__number_ranges,
  (ProtobufCMessageInit) pgcodec__root_ent__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor pgcodec__root_idx__field_descriptors[1] =
{
  {
    "entries",
    1,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    PROTOBUF_C_OFFSETOF(PGcodec__RootIdx, n_entries),
    PROTOBUF_C_OFFSETOF(PGcodec__RootIdx, entries),
    &pgcodec__root_ent__descriptor,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned pgcodec__root_idx__field_indices_by_name[] = {
  0,   /* field[0] = entries */
};
static const ProtobufCIntRange pgcodec__root_idx__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor pgcodec__root_idx__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "PGcodec.RootIdx",
  "RootIdx",
  "PGcodec__RootIdx",
  "PGcodec",
  sizeof(PGcodec__RootIdx),
  1,
  pgcodec__root_idx__field_descriptors,
  pgcodec__root_idx__field_indices_by_name,
  1,  pgcodec__root_idx__number_ranges,
  (ProtobufCMessageInit) pgcodec__root_idx__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor pgcodec__table_meta__field_descriptors[3] =
{
  {
    "name",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(PGcodec__TableMeta, name),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "uuid",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(PGcodec__TableMeta, uuid),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "root_id",
    3,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT64,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(PGcodec__TableMeta, root_id),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned pgcodec__table_meta__field_indices_by_name[] = {
  0,   /* field[0] = name */
  2,   /* field[2] = root_id */
  1,   /* field[1] = uuid */
};
static const ProtobufCIntRange pgcodec__table_meta__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor pgcodec__table_meta__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "PGcodec.TableMeta",
  "TableMeta",
  "PGcodec__TableMeta",
  "PGcodec",
  sizeof(PGcodec__TableMeta),
  3,
  pgcodec__table_meta__field_descriptors,
  pgcodec__table_meta__field_indices_by_name,
  1,  pgcodec__table_meta__number_ranges,
  (ProtobufCMessageInit) pgcodec__table_meta__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor pgcodec__superblock__field_descriptors[2] =
{
  {
    "uuid",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(PGcodec__Superblock, uuid),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "tables",
    2,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    PROTOBUF_C_OFFSETOF(PGcodec__Superblock, n_tables),
    PROTOBUF_C_OFFSETOF(PGcodec__Superblock, tables),
    &pgcodec__table_meta__descriptor,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned pgcodec__superblock__field_indices_by_name[] = {
  1,   /* field[1] = tables */
  0,   /* field[0] = uuid */
};
static const ProtobufCIntRange pgcodec__superblock__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor pgcodec__superblock__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "PGcodec.Superblock",
  "Superblock",
  "PGcodec__Superblock",
  "PGcodec",
  sizeof(PGcodec__Superblock),
  2,
  pgcodec__superblock__field_descriptors,
  pgcodec__superblock__field_indices_by_name,
  1,  pgcodec__superblock__number_ranges,
  (ProtobufCMessageInit) pgcodec__superblock__init,
  NULL,NULL,NULL    /* reserved[123] */
};
