/* Generated by the protocol buffer compiler.  DO NOT EDIT! */

#ifndef PROTOBUF_C_PGcodec_2eproto__INCLUDED
#define PROTOBUF_C_PGcodec_2eproto__INCLUDED

#include <google/protobuf-c/protobuf-c.h>

PROTOBUF_C_BEGIN_DECLS


typedef struct _PGcodec__RootEnt PGcodec__RootEnt;
typedef struct _PGcodec__RootIdx PGcodec__RootIdx;
typedef struct _PGcodec__TableMeta PGcodec__TableMeta;
typedef struct _PGcodec__Superblock PGcodec__Superblock;


/* --- enums --- */


/* --- messages --- */

struct  _PGcodec__RootEnt
{
  ProtobufCMessage base;
  ProtobufCBinaryData key;
  uint32_t n_records;
  uint64_t file_id;
};
#define PGCODEC__ROOT_ENT__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&pgcodec__root_ent__descriptor) \
    , {0,NULL}, 0, 0 }


struct  _PGcodec__RootIdx
{
  ProtobufCMessage base;
  size_t n_entries;
  PGcodec__RootEnt **entries;
};
#define PGCODEC__ROOT_IDX__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&pgcodec__root_idx__descriptor) \
    , 0,NULL }


struct  _PGcodec__TableMeta
{
  ProtobufCMessage base;
  char *name;
  char *uuid;
  uint64_t root_id;
};
#define PGCODEC__TABLE_META__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&pgcodec__table_meta__descriptor) \
    , NULL, NULL, 0 }


struct  _PGcodec__Superblock
{
  ProtobufCMessage base;
  char *uuid;
  size_t n_tables;
  PGcodec__TableMeta **tables;
};
#define PGCODEC__SUPERBLOCK__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&pgcodec__superblock__descriptor) \
    , NULL, 0,NULL }


/* PGcodec__RootEnt methods */
void   pgcodec__root_ent__init
                     (PGcodec__RootEnt         *message);
size_t pgcodec__root_ent__get_packed_size
                     (const PGcodec__RootEnt   *message);
size_t pgcodec__root_ent__pack
                     (const PGcodec__RootEnt   *message,
                      uint8_t             *out);
size_t pgcodec__root_ent__pack_to_buffer
                     (const PGcodec__RootEnt   *message,
                      ProtobufCBuffer     *buffer);
PGcodec__RootEnt *
       pgcodec__root_ent__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   pgcodec__root_ent__free_unpacked
                     (PGcodec__RootEnt *message,
                      ProtobufCAllocator *allocator);
/* PGcodec__RootIdx methods */
void   pgcodec__root_idx__init
                     (PGcodec__RootIdx         *message);
size_t pgcodec__root_idx__get_packed_size
                     (const PGcodec__RootIdx   *message);
size_t pgcodec__root_idx__pack
                     (const PGcodec__RootIdx   *message,
                      uint8_t             *out);
size_t pgcodec__root_idx__pack_to_buffer
                     (const PGcodec__RootIdx   *message,
                      ProtobufCBuffer     *buffer);
PGcodec__RootIdx *
       pgcodec__root_idx__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   pgcodec__root_idx__free_unpacked
                     (PGcodec__RootIdx *message,
                      ProtobufCAllocator *allocator);
/* PGcodec__TableMeta methods */
void   pgcodec__table_meta__init
                     (PGcodec__TableMeta         *message);
size_t pgcodec__table_meta__get_packed_size
                     (const PGcodec__TableMeta   *message);
size_t pgcodec__table_meta__pack
                     (const PGcodec__TableMeta   *message,
                      uint8_t             *out);
size_t pgcodec__table_meta__pack_to_buffer
                     (const PGcodec__TableMeta   *message,
                      ProtobufCBuffer     *buffer);
PGcodec__TableMeta *
       pgcodec__table_meta__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   pgcodec__table_meta__free_unpacked
                     (PGcodec__TableMeta *message,
                      ProtobufCAllocator *allocator);
/* PGcodec__Superblock methods */
void   pgcodec__superblock__init
                     (PGcodec__Superblock         *message);
size_t pgcodec__superblock__get_packed_size
                     (const PGcodec__Superblock   *message);
size_t pgcodec__superblock__pack
                     (const PGcodec__Superblock   *message,
                      uint8_t             *out);
size_t pgcodec__superblock__pack_to_buffer
                     (const PGcodec__Superblock   *message,
                      ProtobufCBuffer     *buffer);
PGcodec__Superblock *
       pgcodec__superblock__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   pgcodec__superblock__free_unpacked
                     (PGcodec__Superblock *message,
                      ProtobufCAllocator *allocator);
/* --- per-message closures --- */

typedef void (*PGcodec__RootEnt_Closure)
                 (const PGcodec__RootEnt *message,
                  void *closure_data);
typedef void (*PGcodec__RootIdx_Closure)
                 (const PGcodec__RootIdx *message,
                  void *closure_data);
typedef void (*PGcodec__TableMeta_Closure)
                 (const PGcodec__TableMeta *message,
                  void *closure_data);
typedef void (*PGcodec__Superblock_Closure)
                 (const PGcodec__Superblock *message,
                  void *closure_data);

/* --- services --- */


/* --- descriptors --- */

extern const ProtobufCMessageDescriptor pgcodec__root_ent__descriptor;
extern const ProtobufCMessageDescriptor pgcodec__root_idx__descriptor;
extern const ProtobufCMessageDescriptor pgcodec__table_meta__descriptor;
extern const ProtobufCMessageDescriptor pgcodec__superblock__descriptor;

PROTOBUF_C_END_DECLS


#endif  /* PROTOBUF_PGcodec_2eproto__INCLUDED */
